apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    basicAuth: false
    jsonData:
      version: Flux
      organization: dcs
    secureJsonData:
      token: influx-token
