// <auto-generated />
using System;
using EquipmentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentService.Migrations
{
    [DbContext(typeof(EquipmentDbContext))]
    partial class EquipmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentService.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Capacity")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Operating");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TagNumber")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Equipment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500.0,
                            CreatedAt = new DateTime(2025, 11, 16, 15, 46, 23, 946, DateTimeKind.Utc).AddTicks(6635),
                            InstallDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Crude Feed Pump",
                            Status = "Operating",
                            TagNumber = "P-101",
                            Type = "Centrifugal Pump",
                            Unit = "m³/h"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50.0,
                            CreatedAt = new DateTime(2025, 11, 16, 15, 46, 23, 946, DateTimeKind.Utc).AddTicks(6640),
                            InstallDate = new DateTime(2019, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Crude Preheat Exchanger",
                            Status = "Operating",
                            TagNumber = "E-201",
                            Type = "Shell & Tube Heat Exchanger",
                            Unit = "MW"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100000.0,
                            CreatedAt = new DateTime(2025, 11, 16, 15, 46, 23, 946, DateTimeKind.Utc).AddTicks(6643),
                            InstallDate = new DateTime(2018, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Distillation Column",
                            Status = "Operating",
                            TagNumber = "T-301",
                            Type = "Fractionation Tower",
                            Unit = "bbl/day"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
